name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Log in to Azure Container Registry
        run: cat "${{ secrets.AZURE_CLIENT_SECRET }}" | docker login -u ${{ secrets.AZURE_APPLICATION_ID }} --password-stdin

      - name: Build go binary.
        run: go build emilhodgolden.go

      - name: Run
        run: ./emilhodgolden --go --build
        env:
          AZURE_ACR_NAME_DEV: ${{ secrets.AZURE_ACR_NAME_DEV}}
